#on: [push]
on:
  workflow_dispatch:
name: DockerDeploy

jobs:

    Initiate-Docker-Deployment:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Download Docker Installation Script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke -g Attack_Defense_Lab -n testvm --command-id RunShellScript --scripts "wget -P /tmp https://raw.githubusercontent.com/gyaansastra/Attack-Defense-Lab/dev/scripts/docker.sh"

      - name: Make Script Executable
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke -g Attack_Defense_Lab -n testvm --command-id RunShellScript --scripts "chmod +x /tmp/docker.sh"

      - name: Deploy Docker Package
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke -g Attack_Defense_Lab -n testvm --command-id RunShellScript --scripts "sudo bash /tmp/docker.sh"